account/urls.py
from django.urls import path
from . import views


urlpatterns =[
    path(r'', views.user_login, name='login'),
    path(r'login/', views.user_login, name='login'),
    path(r'register/', views.register, name='register'),
    path(r'register_done/', views.register, name='register_done'),
]

first_news/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from news import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('news/',include(('news.urls', 'news'), namespace='news')),
    path('account/',include(('account.urls', 'account'), namespace='account')),
    path('api/',include(('news.api.urls','api'), namespace='api')),
    url('social-auth/',include('social.apps.django_app.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/api/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
__title__ = ''
__author__ = 'Administrator'
__mtime__ = '2018/4/8'
# code is far away from bugs with the god animal protecting
    I love animals. They taste delicious.
              ┏┓      ┏┓
            ┏┛┻━━━┛┻┓
            ┃      ☃      ┃
            ┃  ┳┛  ┗┳  ┃
            ┃      ┻      ┃
            ┗━┓      ┏━┛
                ┃      ┗━━━┓
                ┃  神兽保佑    ┣┓
                ┃　永无BUG！   ┏┛
                ┗┓┓┏━┳┓┏┛
                  ┃┫┫  ┃┫┫
                  ┗┻┛  ┗┻┛
"""
from django.urls import path
from django.conf.urls import url,include
from . import api_views,api
from rest_framework.authtoken import views


urlpatterns = [
    path('news_list/',api.news_list, name='news_list'),
    path('full/news_list/', api_views.news_list, name='news_list'),

    path(r'token-auth', views.obtain_auth_token),
    path('users_list/', api.users_list, name='users_list'),
    path('full/login/', api_views.login, name="login"),#


    path('news_card/',api.news_card, name="news_card"),
    url(r'news_card/(?P<id>\d+)$', api.news_card, name="news_card"),
    path('comments/',api.comments_get_post,name="comments"),



]

from rest_framework.authtoken import views
urlpatterns += [
    path(r'token-auth', views.obtain_auth_token)
]

news/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'news'
urlpatterns =[
    path(r'', views.index, name='list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', views.news_detail, name='news_detail'),
]

account/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateTimeField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    def __str__(self):
        return "{}个人信息已经更新".format(self.user.username)



from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

news/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from uuslug import slugify
from taggit.managers import TaggableManager
# Create your models here.

class News(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100,default='news')
    image = models.ImageField(upload_to='image/%Y/%m/%d',default=None)
    image_url = models.URLField(default=None)
    content = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    love_times = models.PositiveIntegerField(default=1)
    good_times = models.PositiveIntegerField(default=0)
    bad_times = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='news_created', on_delete=models.CASCADE)

    TAG_CHOICES = (
        ('tech','Tech'),
        ('life','Life'),
        ('music','Music'),
        ('idol','Idol'),
    )
    tag = models.CharField(null=True, blank=True, max_length=5, choices=TAG_CHOICES)



    def get_absolute_url(self):
        #self.slug = slugify(self.slug)
        return reverse('news:news_detail', args=[
                                            self.created.year,
                                            self.created.strftime('%m'),
                                            self.created.strftime('%d'),
                                            self.slug,
                                                    ])

class Comments(models.Model):
    news = models.ForeignKey(News, related_name="comments", on_delete=models.CASCADE)
    name = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="comment_user", on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "Comments by {} on {}".format(self.name,self.news)




class Images(models.Model):
    """
    图片类：
    1 把图片生成url
    2 保存到url到数据库
    3 把图片放到upload
    """
    pass

account/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(label='用户名')
    password = forms.CharField(label='密码',widget=forms.PasswordInput)



class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='密码',widget=forms.PasswordInput)
    password2 = forms.CharField(label='密码2',widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name','email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password']!= cd['password2']:
            raise forms.ValidationError('两个密码不一样')
        return cd['password2']

news/forms.py
from django import forms

from .models import News,Images


class CreateNews(forms.ModelForm):


    class Meta:
        model = News
        fields = ('title','slug','image','image_url','user','content','created','update')

account/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.shortcuts import render
from .forms import LoginForm, RegisterForm


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            # 使用


            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('认证成功')
                else:
                    return HttpResponse('该用户没有权限')

    else:
        """当是被一个get请求时，实例化一个登录表单，交给template渲染"""
        form = LoginForm()
    return render(request, 'account/login.html', {'form':form})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()

            return render(request, 'account/register_done.html',
                          {'new_user':new_user})

    else:
        form = RegisterForm()

    return render(request, 'account/register.html',
                  {'form':form})

news/views.py
from django.shortcuts import render, get_object_or_404

from .models import News

def index(request):
    queryset = request.GET.get('tag')
    if queryset:
        news = News.objects.filter(tag=queryset)
    else:
        news = News.objects.all()

    return render(request, 'news/list.html', {'news':news})



def news_detail(request, year, month, day,slug):
    news_paper = get_object_or_404(News,slug=slug,
                                   created__year=year,
                                   created__month=month,
                                   created__day=day,
                                   )
    return render(request, 'news/news_detail.html', {'news_paper':news_paper})

account/templates/base(1).html
{% load staticfiles %}

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static "images/favicon_1.ico" %}">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-xl bg-success navbar-light" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="#" class="navbar-brand">新鲜事</a>
            </div>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav nav-tabs">
                <li class="nav-item active">APP</li>

                <li class="nav-item">天气</li>
                <li class="nav-item">
                    <a href="{% url "account:login" %}">登录</a>
                </li>
                <li class="nav-item">
                    <a href="{% url "account:register" %}">注册</a>
                </li>
            </ul>

        </div>

    </nav>

    <div id="content">

        {% block content %}
        {% endblock %}
    </div>
</body>

news/templates/api/account.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    
    <script src="{% static 'js/vue.js' %}"></script>
    <!-- 映入 vue vue-router reqwest axios cookie 等js文件   引入cookie.js 来对cookie操作-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js"></script>
    <script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/reqwest/2.0.5/reqwest.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.3/js.cookie.js"></script>
        
    <link rel="shortcut icon" href="{% static 'images/favicon_1.ico' %}">
    <title>注册</title>
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/news_list.css' %}">
</head>


<body id="app">

    {% verbatim %}

    <nav class="navbar navbar-expand-xl bg-success navbar-light" role="navigation" >
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="#" class="navbar-brand">新鲜事</a>
            </div>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav nav-tabs">
                <li class="nav-item active">APP</li>

                <li class="nav-item">天气</li>
                <div v-if="loginshow">
                    <li class="nav-item"  >
                        <!-- <a href="{% url "account:login" %}">登录</a> -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myLogin">登录</button>
                    </li>
                    <li class="nav-item">
                        <!-- <a href="{% url "account:register" %}">注册</a> -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myRegister">注册</button>
                    </li>
                </div>
                <div v-else>
                    <li class="nav-item" >
                        <button> 你好！ {{cur_user}} 。</button>
                    </li>
                    <li class="nav-item">
                        <button>退出</button>
                    </li>
                </div>
            </ul>

        </div>
    </nav>

    <div class="col-auto">
        <div class="panel">
            <router-view></router-view>
        </div>
    </div>
    
    
<!-- 登录 -->
    <div class="modal fade" id="myLogin">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- 模态框头部 -->
                <div class="modal-header">
                    <h4 class="modal-title">Login User</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- 内容 -->
                <div class="modal-body">
                    <form action="." method="POST">
                        
                        <div class="form-group">
                            <label for="userlogin">用户名</label>
                            <input type="text" id="user-login" v-model="username" placeholder="请输入用户名">
                        </div>
                        <div class="form-group">
                            <label for="pwd-login">密码</label>
                            <input type="password" id="pwd-login" v-model="password" placeholder="请输入密码">
                        </div>
                    </form>
                </div>

                <!-- 底部 -->
                <div class="modal-footer">
                    <button @click="login()" class="btn btn-primary" >登录</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>

            </div>
        </div>
    </div>


    <div class="modal fade" id="myRegister">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">注册</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <div class="modal-body">
                    <form action="." method="POST">
                            {% csrf_token %}
                        <div class="form-group">
                            <label for="user">用户名</label>
                            <input type="text" id="user" v-model="newuser.username" placeholder="请输入用户名">
                        </div>
                        <div class="form-group">
                            <label for="pwd">密码</label>
                            <input type="password" id="pwd" v-model="newuser.password" placeholder="请输入密码">
                        </div>
                        <div class="form-group">
                            <label for="pwd2">重复密码</label>
                            <input type="password" id="pwd2" v-model="newuser.password2" placeholder="请重复输入密码">
                        </div>
                        <div class="form-group">
                                <label for="email">邮箱</label>
                                <input type="email" id="email" v-model="newuser.email" placeholder="请输入邮箱">
                            </div>                                     
                    </form>
                </div>

                <div class="modal-footer">
                    <button @click="register()" type="submit" class="btn btn-primary">注册</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>

    {% endverbatim %}

    <script>
        var test = new Vue({
            el:"#app",
            data:{
                users:[],
                newuser:{username:'',password:null,password2:null,email:null},
                loginshow:true,
                cur_user:'',
                username:'',
                password:null,

            },
            methods: {
                getUserData(){
                    var self = this;
                    
                    axios.get('/api/users_list/').then(
                        function(response){
                            console.log(response.data);
                            

                        }).catch(
                            function(error){
                                console.log(error);
                            }
                        )
                },
                login(){
                    var self = this;
                    
                    axios.post('/api/users_list/',{
                        username:this.username,
                        password:this.password,
                    }).then(
                        function(response){
                            console.log(response.data);
                            test.cur_user = response.data['username'];
                            test.loginshow = false;                               
                        }).catch(
                            function(error){
                                console.log(error);
                            }
                        )
                },
                register(){

                    if(this.newuser.username===''){
                        alert("姓名不能为空");
                        return;
                    }

                    if(this.newuser.email===''){
                        alert("邮箱不能为空");
                        return;
                    }

                    if(this.newuser.password===''){
                        alert("密码不能为空");
                        return;
                    }

                    if(this.newuser.password2===''){
                        alert("密码不能为空");
                        return;
                    }

                    if(this.newuser.password===this.newuser.password2){
                        alert("两次密码不一致");
                        return;
                    }

                    axios.post('/api/users_list/',{
                        username:this.newuser.username,
                        password:this.newuser.password,
                        email:this.newuser.email,    
                    }).then(
                        function(response){
                            console.log(response.data);
                        }).catch(function(error){
                            console.log(error);
                        }
                    )
                }

            },
            // ready:function(){
            //     this.getUserData();
            // }

        })                   
    </script>
</body>

</html>

news/templates/api/news_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}I le hu{% endblock %}
<style>
    .touxiang{
        float:left;

    }
    img{
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
</style>        
        
{% block content %}


    {% verbatim %}
    <div class="mycard" id="app">
        <div class="container" v-for="vid in vids" style="margin-top: 50px;">
            <!-- 用户头像 -->
            <div class="col-1">
                <img :src="vid.image" alt="" class="rounded-circle" style="width: 100px;float: left;">        
            </div>
            
            <!-- 卡片列表 -->
            <div class="card bg-secondary text-white">
                <div class="card-body">
                    <h4 class="card-title">{{vid.title}}</h4>
                    <div class="card-header">
                        <p>{{vid.created}}</p>
                        <p>{{vid.user}}</p>
                    </div>
                    <p class="card-text">{{ vid.content|truncatewords:100 }}</p>
                    
                    <img :src="vid.image_url" alt="">
                    <img :src="vid.image" alt="">
                    <!-- <a href="?tag={{ vid.tag }}">{{ vids.tag }}</a> -->
                </div>
                <div class="card-footer">
                    <div class="row">
                        <button class="col-1" @click="agree(vid)">点赞 {{vid.good_times}}</button>
                        <button class="col-1" @click="disagree">拉黑 {{vid.bad_times}}</button>
                        <button class="col-1" @click="change_comment">评论</button>
                    </div>
                    <div v-show="comments_show">
                        <input type="text" v-model="comment">
                        <button type="submit" @click="creatComment(vid)">OK</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endverbatim %}

    <script>

        var vm = new Vue({
            el:"#app",
            data:{
                message:'',
                show:false,
                chosen:"all",
                comment:"",
                comments_show:false,
                vids:[],

            },
            methods:{
                agree:function(data) {                    
                    data.good_times += 1;
                    // console.log("goodtimes");
                    // console.log(data.good_times);
                    vm.sendData(data);
                    
                },
                disagree:function(data) {
                    data.bad_times +=1;
                    vm.sendData(data);
                },

                //通过状态值 改变评论栏是否 出现
                change_comment:function(){
                    vm.comments_show = !vm.comments_show;
                },

                //发送创建评论
                creatComment:function(vid){
                    console.log("vid.id is "+vid.id);
                    axios({
                        url:"/api/comments/",
                        method:"post",
                        headers:Cookies.get('token')? {'Authorization': 'Token ' + Cookies.get('token')}:{},
                        data:{
                            name:Cookies.get('username')? Cookies.get('username'):'',
                            body:vm.comment,
                            news_id:2,

                        }
                    })
                },

                getData:function () {
                    var self = this;

                    // reqwest({
                    //     url:'http://127.0.0.1:8000/api/news_list/',
                    //     type:'json',
                    //     method:'get',
                    //     headers:Cookies.get('token')? {'Authorization': 'Token ' + Cookies.get('token')}:{},

                    //     success:function (resp) {
                    //         self.vids = resp;

                    //     }
                    // })
                    // reqwest 已验证是可以行的

                    axios({
                        url:'/api/news_list/',
                        method:'get',
                        headers:Cookies.get('token')? {'Authorization': 'Token ' + Cookies.get('token')}:{},
                    }).then(
                        function(response){
                            self.vids = response.data;
                            
                            console.log("成功取回数据");
                            console.log(response.data);
                        }
                    ).catch(
                        function(error){
                            console.log("发生错误，如下：");
                            console.log(error);
                        }

                    )   
                },

                sendData:function(Data){
                    console.log("看到user_id");
                    console.log(Data);
                    console.log(Data.user.id);
                    var self = this;
                    axios({
                        url:"/api/news_card/",
                        method:"put",
                        headers:Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        data:{
                            title:Data.title,
                            id:Data.user.id,
                            username:Data.user.username,
                            good_times:Data.good_times,
                            bad_times:Data.bad_times,
                        }
                    }).then(
                        function(response){
                            console.log("修改成功");
                        }
                    ).catch(
                        function(error){
                            console.log(error);
                        }
                    )                        
                },

            },
            ready:function () {
                this.getData()
            }
        })
    </script>
    
{% endblock %}
        

news/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1,1"> -->

    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    
    <!-- 映入 vue vue-router reqwest axios cookie 等js文件   引入cookie.js 来对cookie操作-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js"></script>
    <script src="https://unpkg.com/vue-router@2.0.0/dist/vue-router.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/reqwest/2.0.5/reqwest.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.3/js.cookie.js"></script>
        
    <link rel="shortcut icon" href="{% static 'images/favicon_1.ico' %}">
    <title>{% block title %}i乐乎{% endblock %}</title>
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/news_list.css' %}">
    <style>
        .carousel-inner img {
            width: 100%;
            height: 100%;
        }

        .float-buttom{
            position: fixed;
        }

            
    </style>
</head> 
<body>
    <nav class="navbar navbar-expand-xl bg-success navbar-light" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="#" class="navbar-brand">新鲜事</a>
            </div>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav nav-tabs">
                <li class="nav-item active">首页</li>
                <li class="nav-item">话题广场</li>
                <li class="nav-item">小密圈</li>
                <li class="nav-item">APP</li>
                <li class="nav-item">
                    <a href="{% url "api:login" %}">登录/注册</a>
                </li>
                <li class="nav-item">
                    <a href="{% url "account:register" %}">注册</a>
                </li>
            </ul>

        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>

{% block footer %}
{% endblock %}

news/templates/news/list.html
{% extends "base.html" %}
{% load staticfiles %}

<link rel="shortcut icon" href="{% static " images/favicon_1.ico " %}">
{% block title %}新鲜事{% endblock %}
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "css/news_list.css" %}">
<!-- <link rel="stylesheet" href="../../static/css/bootstrap.css">
<link rel="stylesheet" href="../../static/css/news_list.css"> -->
<style>


</style>

<body id="app">
    {% block content %}
    <div class="col-1 left-colum">
        <nav class="navbar bg-secondary navbar-dark">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <img src="{% static "images/logo.png" %}" style="width:100px">
                </li>
                <li class="nav-item">推荐</li>
                <li class="nav-item">热点</li>
                <li class="nav-item">图片</li>
                <li class="nav-item">科技</li>
                <li class="nav-item">娱乐</li>
                <li class="nav-item">游戏</li>
                <li class="nav-item">体育</li>
                <li class="nav-item">汽车</li>
                <li class="nav-item">财经</li>
                <li class="nav-item">搞笑</li>
                <li class="nav-item">更多</li>

            </ul>
        </nav>
    </div>

    <div class="container">
        {% for new in news %}
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{new.title}}</h4>
                <p class="card-text">{{ new.content|truncatewords:100 }}</p>
                <a href="?tag={{ new.tag }}">{{ new.tag }}</a>
            </div>
    </div>

        {% endfor %}
    </div>

    {% endblock %}


</body>

news/templates/news/news_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} 世界 {% endblock %}

{%block content %}
  <div class="pager">
      <p>{{ news_paper.title }}</p>
      <p>{{ news_paper.content }}</p>

  </div>

{% endblock %}